### ISSUE TITLE
HttpLogger.log

### ISSUE THREAD

**Issue by josef2600** [pschatzmann/TinyHttp#2] opened 2022-11-17 18:29 UTC
i don't know, maybe i am doing something wrong? but i had error to compile this lib in audio lib, and got error for HttpLogger.log not recognized, then i add `#include "HttpLogger.h"
` in the file `HttpChunkWriter.h` and that error is gone. i have another error for get `AudioServerEx.h:67:64: error: 'GET' is not a member of 'tinyhttp'
` currently working on it. if i found the problem i will tell you.
thank you

**Comment by pschatzmann** [comment] 2022-11-17 18:32
How can I reproduce your issue ?

**Comment by josef2600** [comment] 2022-11-17 18:41
in the file:
`streams-generator-webserverex_wav.ino` from `arduino-audio-tools-main\examples\examples-webserver\streams-generator-webserverex_wav`
first i got error on the top, then i got error for this: 
`In file included from C:\Users\Josef\Desktop\ESP32 Audio Tutorial with lots of examples\arduino-audio-tools-main\examples\examples-webserver\streams-generator-webserverex_wav\streams-generator-webserverex_wav.ino:15:
C:\Users\Josef\Documents\Arduino\libraries\audio_tools\src/AudioLibs/AudioServerEx.h: In member function 'virtual bool audio_tools::AudioServerEx::begin()':
C:\Users\Josef\Documents\Arduino\libraries\audio_tools\src/AudioLibs/AudioServerEx.h:67:64: error: 'GET' is not a member of 'tinyhttp'
             p_stream = new ExtensionStream(info.path,tinyhttp::GET, info.mime );
                                                                ^~~
C:\Users\Josef\Documents\Arduino\libraries\audio_tools\src/AudioLibs/AudioServerEx.h:67:64: note: suggested alternative: 'T_GET'
             p_stream = new ExtensionStream(info.path,tinyhttp::GET, info.mime );
                                                                ^~~
                                                                T_GET
Multiple libraries were found for "SD.h"
 Used: C:\Users\Josef\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.5\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Josef\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.5\libraries\WiFi
 Not used: C:\Users\Josef\Documents\Arduino\libraries\WiFiEspAT
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
`

**Comment by josef2600** [comment] 2022-11-17 18:44
i have not changed anything except the added #include "HttpLogger.h"  in file HttpChunkWriter.h

**Comment by pschatzmann** [comment] 2022-11-17 18:46
Is this with an ESP32 ?
Did you install https://github.com/pschatzmann/TinyHttp.git ?

**Comment by pschatzmann** [comment] 2022-11-17 18:57
After updating TinyHttp I also getting an error because GET has been renamed to T_GET.
I just committed a correction to the AudioTools project

**Comment by josef2600** [comment] 2022-11-17 19:05
thank you.

**Comment by josef2600** [comment] 2022-11-17 19:21
it has compiled it. just please add #include `"HttpLogger.h"` in the file `HttpChunkWriter.h` too. for me, without it, it makes error.

**Comment by pschatzmann** [comment] 2022-11-17 19:27
ok, done...

**Closed** 2022-11-17 19:31 UTC
